language: bash

services:
 - docker

script:
  - |
    set -e
    make build
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
    docker tag timelapse kennep/timelapse
    docker push kennep/timelapse
