name: "$(Build.SourceBranchName)-$(Build.SourceVersion)"

steps:
- task: Docker@1
  displayName: 'Build docker image'
  inputs:
    dockerFile: ./Dockerfile
    imageName: 'kennep/timelapse:$(Build.SourceBranchName)'

