version: 2
jobs:
  build:
    docker:
      - image: docker:18.09
    steps:
      - checkout
      - setup_remote_docker:
          version: "18.09.3"
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build . -t kennep/timelapse
      - run:
          name: Depoy Docker image
          contexts:
            - DockerHub
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker push kennep/timelapse

workflows:    
  build:
    jobs:
      - build:
          context: DockerHub
